apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: leakybucket
  description: Leaky bucket implementation in Go with support for different backends (redis, in-memory)
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
