version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Clever/leakybucket
    docker:
    - image: circleci/golang:1.10.3-stretch
    - image: redis@sha256:858b1677143e9f8455821881115e276f6177221de1c663d0abef9b2fda02d065
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - setup_remote_docker
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run: ulimit -n 2560
    - run: make test
    - run: $HOME/ci-scripts/circleci/report-card $RC_DOCKER_USER $RC_DOCKER_PASS "$RC_DOCKER_EMAIL" $RC_GITHUB_TOKEN
    - run:
        command: |-
          cd /tmp/ && wget https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
          sudo apt-get update
          sudo apt-get install python-dev
          sudo pip install --upgrade awscli && aws --version
          pip install --upgrade --user awscli
        name: Install awscli for ECR publish
